version: 2.1 
jobs: 
  build: 
    working_directory: ~/vscode-iq-plugin 
    docker: 
      - image: circleci/node:12.20.1
    steps: 
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install npm dependencies...weeeeee
          command: yarn
      - save_cache: 
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: 
          name: build
          command: yarn run build
  release:
    working_directory: ~/vscode-iq-plugin 
    docker: 
      - image: circleci/node:12.20.1
    steps:
      - checkout
      - run: 
          name: Allow global installs of npm packages
          command: sudo chown -R circleci:circleci /usr/local/lib && sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build extension
          command: yarn run build
      - run: 
          name: Install publishing packages 
          command: yarn global add vsce semantic-release @semantic-release/changelog @semantic-release/git@7.1.0-beta.11 @semantic-release/npm
      - run: 
          name: Attempt publish to GitHub
          command: npx semantic-release -b master
      - run: 
          name: Package for Visual Studio Code Extension Marketplace
          command: vsce package --yarn
      - run: 
          name: Publish to Visual Studio Code Extension Marketplace
          command: vsce publish --yarn -p $VSCODE_TOKEN
      - run:
          name: Publish to Open VSX
          command: npx ovsx publish -p $VSX_TOKEN

workflows:
  version: 2.1
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: master
          context: vscode-plugin
          requires:
            - build

  build_nightly:
    triggers:
      - schedule:
          cron: "20 20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
